baseurl      = "https://rollofdeath.github.io"
title        = "RollOfDeath"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "The best cat is the cat which is fishing for the shell"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Metadata mostly used in document's head
  # description = "My new homepage or blog"
  # keywords = "homepage, blog"
  # images = [""]

# [taxonomies]
#     category = "blog"
#     tag      = "tags"
#     series   = "series"

[languages]
  [languages.en]
    # Change this for tab name 
    title = "RollOfDeath"
    subtitle = "Info Sec Blog"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      # Change Title
      logoText = "/home/rod #"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  [[menu.main]]
  #  identifier = "writeups"
  #  name       = "write-ups"
  #  url        = "/write-ups"

    identifier = "tags"
    name       = "Tags"
    url        = "/tags"

  [[params.social]]
    name = "tryhackme"
    url = "https://tryhackme.com/p/RollOfDeath"

  [[params.social]]
    name = "hackthebox"
    url = ""

  [[params.social]]
    name = "github"
    url = "https://github.com/rollofdeath"
